services:
  mariadb:
    image: mariadb
    restart: always
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/:rw
      - ~/database:/var/lib/mysql
    ports: 
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  library-server:
    build: .
    command: npm run dev
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    ports:
      - ${PORT:-3000}:${PORT:-3000}
    expose:
      - ${PORT:-3000}
    depends_on:
      - mariadb
    environment:
      MYSQL_HOST: mariadb


networks:
  internalnet:
    driver: bridge
